# URL de conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist 
# Usuário do Postgres
spring.datasource.username=postgres
# Senha do usuario
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto SQL específico
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Como criar/atualizar tabelas
spring.jpa.hibernate.ddl-auto=update

