CREATE TABLE users(
 id UUID PRIMARY KEY,
 login VARCHAR(150) NOT NULL UNIQUE,
 password VARCHAR(10) NOT NULL,
 role VARCHAR (5) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks(

id UUID PRIMARY KEY,
user_id UUID NOT NULL REFERENCES users(id),
descricao TEXT,
titulo VARCHAR(250) NOT NULL,
data_inicio TIMESTAMP NOT NULL,
data_fim TIMESTAMP NOT NULL,
finalizar_tarefa BOOLEAN,
criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);